---
- name: get kernel release
  shell: uname -r
  register: get_kernel_release

- name: install required packages
  apt:
    name: '{{ item }}'
  with_items:
    - apt-transport-https
    - ca-certificates
    - linux-image-extra-{{ get_kernel_release.stdout }}

- name: add new gpg key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: create docker.list
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
  register: create_docker_list

- name: update apt package index
  apt:
    update_cache: yes
  when: create_docker_list|changed
